### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by roland-d**
Hello @astridx 

Here is my first commit with fixes for code quality.

### CODE REVIEW

**Comment by astridx** [comment]
@roland-d Thank you.

**Comment by astridx** [comment]
@roland-d 
I have now added your improvements to each of the branches for the tutorial, and I've gone further with the text explanations for the first chapter. Maybe you also like to look/check:

Here the code/diff for the first chapter/branch: https://github.com/astridx/boilerplate/compare/astridx:t0...t1
In summary this are all new files on the begin. I think this code is correct now. The language files are still missing here. They will be added in a later chapter.

Here the text for the first chapter: https://github.com/astridx/boilerplate/wiki/1.-Developing-a-Basic-Component. You find this text in the Readme, too. If you like I would be happy about improvements in a PR. For me it is very difficult to write in English.

Next weekend I will work on the second chapter code. Here is the diff: https://github.com/astridx/boilerplate/compare/astridx:t1...t2

There is a release for the first chapter: https://github.com/astridx/boilerplate/releases/tag/v1.0.0

**Comment by roland-d** [comment]
Hello @astridx I will have a read through when I get some time. In the meantime I have been talking to JetBrains and they have agreed with my proposal to move forward in supporting Joomla via the boilerplate. 

The plan is to create the following branches:
  
- feature/j3component
- feature/j4component
- feature/plugins
- feature/module
- feature/template

We can merge your branch into the `feature/j4component` and make this available in PhpStorm if that is OK for you.

**Comment by astridx** [comment]
For me, it's OK if you merge the code in your repo/to PhpStorm.

Unfortunately I did not have as much time in the last weeks as I would like. I also believe that there will be a few changes in Joomla. At the moment there are a few changes in the datetime columns in the database. I would like to get that in when I go through the files next time. At the moment I am not sure if it break something.

But as already written. If you like my code, I'll be glad if you merge it.

**Comment by roland-d** [comment]
> But as already written. If you like my code, I'll be glad if you merge it.

Super thank you.

As for the core changes, yes, we are working on removing the default datetime values from `0000-00-00 00:00:00` to `NULL` to prevent issues with newer MySQL versions. Some other columns will get the current date time where it is logical.

**Pull request closed without merging**
